AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AI Connective Backend - Multi-model AI chat API with RAG support

Globals:
  Function:
    Timeout: 120
    MemorySize: 512
    Runtime: nodejs20.x
    Architectures:
      - x86_64
    Environment:
      Variables:
        BEDROCK_REGION: !Ref AWS::Region
        GEMINI_API_KEY: !Ref GeminiApiKey
        FILES_BUCKET: !Ref FilesBucket
        MAIN_TABLE: !Ref MainTable

Parameters:
  GeminiApiKey:
    Type: String
    Description: Google Gemini API Key
    NoEcho: true
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - staging
      - prod

Resources:
  # ============================================
  # S3 Bucket for Files
  # ============================================
  FilesBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ai-connective-files-${Environment}-${AWS::AccountId}
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - '*'
            AllowedMethods:
              - GET
              - PUT
              - POST
              - DELETE
            AllowedOrigins:
              - '*'
            MaxAge: 3600
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldTempFiles
            Prefix: temp/
            Status: Enabled
            ExpirationInDays: 1

  # ============================================
  # DynamoDB Table (Single Table Design)
  # ============================================
  MainTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ai-connective-${Environment}
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
        - AttributeName: GSI1PK
          AttributeType: S
        - AttributeName: GSI1SK
          AttributeType: S
        - AttributeName: GSI2PK
          AttributeType: S
        - AttributeName: GSI2SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: GSI1
          KeySchema:
            - AttributeName: GSI1PK
              KeyType: HASH
            - AttributeName: GSI1SK
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: GSI2
          KeySchema:
            - AttributeName: GSI2PK
              KeyType: HASH
            - AttributeName: GSI2SK
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true

  # ============================================
  # API Gateway
  # ============================================
  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref Environment
      Cors:
        AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
        AllowHeaders: "'Content-Type,Authorization,X-Amz-Date,X-Api-Key,X-Amz-Security-Token'"
        AllowOrigin: "'*'"

  # ============================================
  # Chat Lambda Function
  # ============================================
  ChatFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ai-connective-chat-${Environment}
      CodeUri: .
      Handler: chat.handler
      Description: Handles chat requests to multiple AI models
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - bedrock:InvokeModel
                - bedrock:InvokeModelWithResponseStream
              Resource: '*'
        - DynamoDBCrudPolicy:
            TableName: !Ref MainTable
        - S3ReadPolicy:
            BucketName: !Ref FilesBucket
      Events:
        ChatApi:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /chat
            Method: POST
        ChatApiOptions:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /chat
            Method: OPTIONS
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2022
        Sourcemap: true
        EntryPoints:
          - src/handlers/chat.ts
        External:
          - '@aws-sdk/*'

  # ============================================
  # Models Lambda Function
  # ============================================
  ModelsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ai-connective-models-${Environment}
      CodeUri: .
      Handler: chat.modelsHandler
      Description: Returns available AI models
      Events:
        ModelsApi:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /models
            Method: GET
        ModelsApiOptions:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /models
            Method: OPTIONS
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2022
        Sourcemap: true
        EntryPoints:
          - src/handlers/chat.ts
        External:
          - '@aws-sdk/*'

  # ============================================
  # Files Lambda Function
  # ============================================
  FilesFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ai-connective-files-${Environment}
      CodeUri: .
      Handler: files.handler
      Description: Handles file uploads and management
      MemorySize: 1024
      Timeout: 300
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref FilesBucket
        - DynamoDBCrudPolicy:
            TableName: !Ref MainTable
      Events:
        UploadApi:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /files/upload
            Method: POST
        ListFilesApi:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /files
            Method: GET
        GetFileApi:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /files/{fileId}
            Method: GET
        DeleteFileApi:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /files/{fileId}
            Method: DELETE
        QueryFileApi:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /files/{fileId}/query
            Method: POST
        FilesOptionsApi:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /files
            Method: OPTIONS
        FilesUploadOptionsApi:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /files/upload
            Method: OPTIONS
        FilesIdOptionsApi:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /files/{fileId}
            Method: OPTIONS
        FilesQueryOptionsApi:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /files/{fileId}/query
            Method: OPTIONS
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2022
        Sourcemap: true
        EntryPoints:
          - src/handlers/files.ts
        External:
          - '@aws-sdk/*'

  # ============================================
  # Conversations Lambda Function
  # ============================================
  ConversationsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ai-connective-conversations-${Environment}
      CodeUri: .
      Handler: conversations.handler
      Description: Handles conversation history
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref MainTable
      Events:
        ListConversationsApi:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /conversations
            Method: GET
        GetConversationApi:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /conversations/{conversationId}
            Method: GET
        DeleteConversationApi:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /conversations/{conversationId}
            Method: DELETE
        ConversationsOptionsApi:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /conversations
            Method: OPTIONS
        ConversationIdOptionsApi:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /conversations/{conversationId}
            Method: OPTIONS
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2022
        Sourcemap: true
        EntryPoints:
          - src/handlers/conversations.ts
        External:
          - '@aws-sdk/*'

Outputs:
  ApiEndpoint:
    Description: API Gateway endpoint URL
    Value: !Sub https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/${Environment}
  FilesBucketName:
    Description: S3 bucket for files
    Value: !Ref FilesBucket
  MainTableName:
    Description: DynamoDB table name
    Value: !Ref MainTable
  ChatFunctionArn:
    Description: Chat Lambda Function ARN
    Value: !GetAtt ChatFunction.Arn
  ModelsFunctionArn:
    Description: Models Lambda Function ARN
    Value: !GetAtt ModelsFunction.Arn
  FilesFunctionArn:
    Description: Files Lambda Function ARN
    Value: !GetAtt FilesFunction.Arn
  ConversationsFunctionArn:
    Description: Conversations Lambda Function ARN
    Value: !GetAtt ConversationsFunction.Arn
